name: Push (Lint, Security Scan, Test)

on:
  push:
    branches:
      - "main"

jobs:
  lint-security-test:
    runs-on: ubuntu-22.04

    services:
      # Localstack is required for integration tests 
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        options: >-
          --health-cmd "curl -s http://localhost:4566/_localstack/health | grep '\"services\":' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.1"

      - name: Install dependencies
        run: python -m pip install --upgrade pip .[dev,test]

      - name: Run code style linter
        run: flake8 src/obfuscator

      - name: Run security check linter
        run: bandit -r src/obfuscator

      - name: Run unit & integration tests
        run: PYTHONPATH=$(pwd) pytest -vvvrP tests
