name: Release (Build, Publish)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.1"

      - name: Build Python package
        run: |
          python -m pip install --upgrade pip build
          python -m build  # This creates the .tar.gz and .whl files

      - name: Upload Python package to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*

